using System.Reflection;
using System.Text.Json;
using PKHeX.Core;
var type=Assembly.Load("PKHeXBridge").GetType("EditorSession")!;
var saveField=type.GetField("save",BindingFlags.Instance|BindingFlags.NonPublic)!;int checks=0;
object Session(SaveFile save){var s=Activator.CreateInstance(type,new object[]{null!})!;saveField.SetValue(s,save);return s;}
JsonElement Request(object s,object r){using var doc=JsonDocument.Parse(JsonSerializer.Serialize(r));checks++;try{return JsonSerializer.SerializeToElement(type.GetMethod("Handle")!.Invoke(s,new object[]{doc.RootElement})!);}catch(TargetInvocationException e){throw e.InnerException!;}}
SaveFile Current(object s)=>(SaveFile)saveField.GetValue(s)!;
int Revision(object s)=>Request(s,new{op="state"}).GetProperty("revision").GetInt32();
void Action(object s,string kind,string mode,string id="")=>Request(s,new{op="extraSet",kind,mode,id,revision=Revision(s)});
void Edit(object s,string kind,string id,params (string field,string value)[] values)=>Request(s,new{op="extraSet",kind,id,edits=values.Select(x=>new{x.field,x.value}),revision=Revision(s)});
string Value(object s,string kind,string id,string field)=>Request(s,new{op="extraEntry",kind,id}).GetProperty("fields").EnumerateArray().Single(f=>f.GetProperty("id").GetString()==field).GetProperty("value").GetString()!;
void Assert(bool test,string message){checks++;if(!test)throw new Exception(message);}
void Reject(Action action,string message){try{action();}catch(Exception e)when(e.Message!=message){checks++;return;}throw new Exception(message);}
void Roundtrip(object session,string kind,string id,Func<byte[],SaveFile> parse){var before=Request(session,new{op="extraEntry",kind,id}).ToString();var copy=parse(Current(session).Write().ToArray());Assert(copy.ChecksumsValid,kind+" checksum");saveField.SetValue(session,copy);Assert(before==Request(session,new{op="extraEntry",kind,id}).ToString(),kind+" serialized entry");}
foreach(var game in new[]{GameVersion.HG,GameVersion.SS}){
 var sav=new SAV4HGSS(new byte[0x80000]){Version=game};var s=Session(sav);var bytes=sav.Data.ToArray();var page=Request(s,new{op="extraPage",kind="pokeathlon"});Assert(sav.Data.SequenceEqual(bytes),"Pokéathlon read purity");
 foreach(var id in page.GetProperty("entries").EnumerateArray().Select(x=>x.GetProperty("id").GetString()!)){var row=Request(s,new{op="extraEntry",kind="pokeathlon",id});Assert(row.GetProperty("fields").GetArrayLength()>0,"Every Pokéathlon entry opens");}
 Edit(s,"pokeathlon","general",("Points","99999"),("card:26","true"),("shop:11","true"));Assert(((SAV4HGSS)Current(s)).Pokeathlon.FlagsDataCard==1u<<26,"Data card bit");Request(s,new{op="undo"});Assert(((SAV4HGSS)Current(s)).Pokeathlon.Points==0,"Sports undo");Request(s,new{op="redo"});
 Edit(s,"pokeathlon","counters",("Fame","65535"),("TimeSpent","59999"));
 for(int i=0;i<5;i++){Edit(s,"pokeathlon",$"course:{i}",("ScoreMax","999"));Edit(s,"pokeathlon",$"participant:{i}:2",("Species","25"),("Form","1"),("Gender","1"),("IsShiny","true"),("TID16","12345"),("SID16","54321"));}
 for(int i=0;i<10;i++){Edit(s,"pokeathlon",$"best:{i}",("Score","300"),("First","100"));Edit(s,"pokeathlon",$"self:{i}",("Attempts","1234"));Edit(s,"pokeathlon",$"connected:{i}",("Attempts","5678"));foreach(string group in new[]{"self","connected"})Edit(s,"pokeathlon",$"record:{group}:{i}:4",("Record","54321"),("Species:2","493"),("Form:2","1"));Edit(s,"pokeathlon",$"trainer:{i}:4",("OriginalTrainerName","Kai"),("TID16","65535"),("Language","2"));}
 var ath=((SAV4HGSS)Current(s)).Pokeathlon;Assert(ath.GetEventConnection((PokeathlonEvent4)9).Inner.GetRecord(4).Entry2.Species==493,"Nested record written");Assert(ath.GetCourseRecord((PokeathlonStat4)4).GetParticipant(2).SID16==54321,"Boxed participant write");
 Action(s,"pokeathlon","medals");Assert(((SAV4HGSS)Current(s)).Pokeathlon.Medals.GetTotalCount()==2465,"All medals");Edit(s,"pokeathlon","medal:493",("Medal:4","false"));Assert(((SAV4HGSS)Current(s)).Pokeathlon.Medals.GetTotalCount()==2464,"Individual medal");
 bytes=Current(s).Data.ToArray();Reject(()=>Edit(s,"pokeathlon","general",("Points","100000")),"Sports bounds");Assert(Current(s).Data.SequenceEqual(bytes),"Sports rejection purity");Roundtrip(s,"pokeathlon","record:connected:9:4",b=>new SAV4HGSS(b));Console.WriteLine("PASS "+game+" full Pokéathlon collections");
}
byte[] HoennFixture(){var data=new byte[0x20000];for(int i=0;i<28;i++){System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(data.AsSpan(i*0x1000+0xFF4),(short)(i%14));System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(data.AsSpan(i*0x1000+0xFF8),0x08012025);if(i%14==0)data.AsSpan(i*0x1000,8).Fill(255);}return data;}
foreach(var game in new[]{GameVersion.R,GameVersion.S,GameVersion.E}){
 SAV3 sav=game==GameVersion.E?new SAV3E(HoennFixture()):new SAV3RS(HoennFixture()){Version=game};sav.Language=2;var m=((ISaveBlock3LargeHoenn)sav.LargeBlock).SecretBases;Assert(m.Count>0,"Seeded base buffer");m.Bases[0].Language=2;m.Bases[0].OriginalTrainerName="Kai";m.Save();var s=Session(sav);var before=sav.Data.ToArray();Request(s,new{op="extraPage",kind="bases3"});Assert(sav.Data.SequenceEqual(before),"Base3 read purity");
 Edit(s,"bases3","base:0",("OriginalTrainerName","Bee"),("TID16","65535"),("SID16","12345"),("BattledToday","true"),("RegistryStatus","1"));
 for(int i=0;i<6;i++)Edit(s,"bases3",$"0:pokemon:{i}",("Species","25"),("PID","4294967295"),("HeldItem","13"),("Move1","85"),("Level","50"),("EVAll","31"));
 Edit(s,"bases3","0:placement:15",("Decoration","100"),("Coordinate","255"));var base3=((ISaveBlock3LargeHoenn)((SAV3)Current(s)).LargeBlock).SecretBases.Bases[0];Assert(base3.Team.Team[5].Species==25&&base3.Team.Team[5].PID==uint.MaxValue,"Base3 team");Assert(base3.GetDecorations()[15]==100,"Base3 decorations");Request(s,new{op="undo"});Assert(Value(s,"bases3","0:placement:15","Decoration")=="0","Base3 undo");Request(s,new{op="redo"});Reject(()=>Edit(s,"bases3","0:pokemon:0",("Level","101")),"Base3 bounds");
 Roundtrip(s,"bases3","0:pokemon:5",b=>game==GameVersion.E?new SAV3E(b):new SAV3RS(b){Version=game});
 var written=Current(s).Write().ToArray();Assert(written.Length>0,"Base3 save export");Assert(Value(s,"bases3","base:0","OriginalTrainerName")=="Bee","Base3 trainer");Console.WriteLine("PASS "+game+" Secret Bases");
}
foreach(var game in new[]{GameVersion.OR,GameVersion.AS}){
 var sav=(SAV6AO)BlankSaveFile.Get(game,"Fixture");var s=Session(sav);var before=sav.Data.ToArray();Request(s,new{op="extraPage",kind="bases6"});Assert(sav.Data.SequenceEqual(before),"Base6 read purity");
 Edit(s,"bases6","base:1",("TrainerName","Kai"),("BaseLocation","12"),("TeamSlogan","Hello!"),("Rank","3"));for(int i=0;i<3;i++)Edit(s,"bases6",$"1:pokemon:{i}",("Species","25"),("Move1","85"),("IV_HP","31"),("CurrentLevel","50"),("IsShiny","true"));Edit(s,"bases6","1:placement:27",("Good","5"),("X","12"),("Y","13"),("Rotation","2"));
 Action(s,"bases6","goods");Assert(((SAV6AO)Current(s)).SecretBase.GetGood(172).Count==25,"Base6 GiveAll");Assert(((SAV6AO)Current(s)).SecretBase.GetSecretBaseOther(0).GetParticipant(2).Species==25,"Base6 participant copyback");Roundtrip(s,"bases6","1:pokemon:2",b=>new SAV6AO(b));
 var dir=Path.Combine(Path.GetTempPath(),"keepsake-parity022-"+Guid.NewGuid());Directory.CreateDirectory(dir);string file=Path.Combine(dir,"Base.sb6");Request(s,new{op="extraExport",kind="bases6",id="base:1",path=file});Assert(new FileInfo(file).Length==SecretBase6Other.SIZE,"Base file bytes");Request(s,new{op="extraSet",kind="bases6",mode="import",id="base:2",path=file,revision=Revision(s)});Assert(Value(s,"bases6","base:2","TrainerName")=="Kai","Base import");Action(s,"bases6","delete","base:1");Assert(Value(s,"bases6","base:1","TrainerName")=="Kai","Base deletion compacts");Request(s,new{op="undo"});Reject(()=>Edit(s,"bases6","1:pokemon:0",("IV_HP","32")),"Base IV bounds");Console.WriteLine("PASS "+game+" Super-Secret Bases and files");
}
foreach(var game in new[]{GameVersion.SN,GameVersion.MN,GameVersion.US,GameVersion.UM}){
 var sav=(SAV7)BlankSaveFile.Get(game,"Fixture");var s=Session(sav);var bytes=sav.Data.ToArray();var page=Request(s,new{op="extraPage",kind="festival"});Assert(sav.Data.SequenceEqual(bytes),"Festival read purity");
 Edit(s,"festival","plaza",("FestivalPlazaName","KeepSake"),("FestaCoins","1234"),("UsedCoins","5678"),("FestaRank","99"),("Date","2026-09-24"),("Hour","13"),("Minute","45"),("Second","30"));Assert(((SAV7)Current(s)).Festa.TotalFestaCoins==6912,"Coin total");Edit(s,"festival","plaza",("Date","2026-09-25"));Assert(((SAV7)Current(s)).Festa.FestaDate!.Value.Hour==13,"Date preserves clock");
 for(int i=0;i<7;i++){Edit(s,"festival",$"facility:{i}",("Type","4"),("Color","2"),("OriginalTrainerName","Kai"),("Gender","1"),("message:3","9999"),("TrainerFesID","0123456789ABCDEF01234567"));Assert(Value(s,"festival",$"facility:{i}","TrainerFesID")=="0123456789ABCDEF01234567","Trainer festival ID");}
 Action(s,"festival","phrases");Assert(Enumerable.Range(0,107).All(i=>((SAV7)Current(s)).Festa.GetFestaPhraseUnlocked(i)),"Unlock phrases");Action(s,"festival","readyrewards");Assert(((SAV7)Current(s)).Festa.GetFestPrizeReceived(10)==1,"Ready reward");Action(s,"festival","receivedrewards");Assert(((SAV7)Current(s)).Festa.GetFestPrizeReceived(0)==2,"Received reward");
 bytes=Current(s).Data.ToArray();Reject(()=>Edit(s,"festival","plaza",("FestaCoins","9999999")),"Coin sum overflow");Assert(Current(s).Data.SequenceEqual(bytes),"Festival atomic rejection");Reject(()=>Edit(s,"festival","facility:0",("TrainerFesID","0")),"Short trainer ID");
 if(game is GameVersion.US or GameVersion.UM){Edit(s,"festival","agency",("Grade","50"),("Defeated","14"),("Chosen","true"),("Invited","true"),("trainer:2","210"));Action(s,"festival","glasses","agency");Assert((((SAV7)Current(s)).Fashion.Data[0xD0]&1)!=0,"Agent sunglasses");Reject(()=>Edit(s,"festival","agency",("Grade","0")),"Agency grade inconsistency");}
 if(game is GameVersion.US or GameVersion.UM){
 var folder=Path.Combine(Path.GetTempPath(),"keepsake-agency022-"+Guid.NewGuid());Directory.CreateDirectory(folder);var mon=new PK7{Species=25,CurrentLevel=50,Move1=85,OriginalTrainerName="Fixture",Language=2};mon.RefreshChecksum();var raw=new byte[mon.SIZE_STORED];mon.WriteDecryptedDataStored(raw);string input=Path.Combine(folder,"fixture.pk7");File.WriteAllBytes(input,raw);
 for(int i=0;i<3;i++){Request(s,new{op="extraSet",kind="festival",mode="import",id="agent:"+i,path=input,revision=Revision(s)});Assert(Request(s,new{op="extraEntry",kind="festival",id="agent:"+i}).GetProperty("name").GetString()!.Contains("Pikachu"),"Agency import");string output=Path.Combine(folder,$"agent{i}.pk7");Request(s,new{op="extraExport",kind="festival",id="agent:"+i,path=output});var copy=new PK7(File.ReadAllBytes(output));Assert(copy.Species==25&&copy.Move1==85&&copy.ChecksumValid,"Agency exported Pokémon");}
 var party=new PK7{Species=133,CurrentLevel=40};((SAV7)Current(s)).SetPartySlotAtIndex(party,0);Action(s,"festival","party","agent:0");Assert(Request(s,new{op="extraEntry",kind="festival",id="agent:0"}).GetProperty("name").GetString()!.Contains("Eevee"),"Agency party copy");Request(s,new{op="undo"});Assert(Request(s,new{op="extraEntry",kind="festival",id="agent:0"}).GetProperty("name").GetString()!.Contains("Pikachu"),"Agency Undo");
 var before=Current(s).Data.ToArray();Reject(()=>Action(s,"festival","party","agent:2"),"Missing agency party slot");Assert(Current(s).Data.SequenceEqual(before),"Invalid party action atomicity");
 Roundtrip(s,"festival","agent:2",b=>new SAV7USUM(b));
 }
 Roundtrip(s,"festival","facility:6",b=>game is GameVersion.US or GameVersion.UM?new SAV7USUM(b):new SAV7SM(b));Request(s,new{op="undo"});Console.WriteLine("PASS "+game+" Festival Plaza");
}
Console.WriteLine($"PASS {checks} new editor requests/assertions; generated fixtures only");
