using System.Text.Json;
using PKHeX.Core;

sealed partial class EditorSession
{
    static int FlyOffset5(SAV5 s)=>s is SAV5BW?0x204B2:0x20392;
    static int[] FlyFlags5(SAV5 s)=>s is SAV5BW?[0,1,2,3,4,5,6,7,8,9,15,11,10,13,12,14]:[24,27,25,8,9,10,11,12,13,14,15,16,17,18,21,20,28,26,66,19,5,6,7,22];
    static string[] FlyNames5(SAV5 s)=>s is SAV5BW?["Nuvema Town","Accumula Town","Striaton City","Nacrene City","Castelia City","Nimbasa City","Driftveil City","Mistralton City","Icirrus City","Opelucid City","Victory Road","Pokémon League","Lacunosa Town","Undella Town","Black City / White Forest","Unity Tower"]:["Aspertia City","Floccesy Town","Virbank City","Nuvema Town","Accumula Town","Striaton City","Nacrene City","Castelia City","Nimbasa City","Driftveil City","Mistralton City","Icirrus City","Opelucid City","Lacunosa Town","Undella Town","Black City / White Forest","Lentimas Town","Humilau City","Victory Road","Pokémon League","Pokéstar Studios","Join Avenue","Pokémon World Tournament","Unity Tower"];
    static readonly string[] SubwayModes5=["Single","Double","MultiNPC","MultiFriends","SuperSingle","SuperDouble","SuperMultiNPC","SuperMultiFriends"];
    ExtraPage ReadMisc5(ExtraTool tool,string? detailId) {
        var s=(SAV5)RequireSave().Clone();var rows=new List<ExtraRow>();void Add(string category,ExtraRow row)=>rows.Add(row with {category=category});
        var names=FlyNames5(s);int offset=FlyOffset5(s);Add("Adventure",ER("fly","Fly destinations",FlyFlags5(s).Select((f,i)=>EV(f.ToString(),names[i],(s.Data[offset+(f>>3)]&(1<<(f&7)))!=0)).ToArray(),actions:[new("flyAll","Unlock All Destinations")]));
        if(s is SAV5BW bw){var fields=new List<ExtraValue>{EP(bw.Misc,"IsLibertyTicketActivated","Liberty Ticket activated"),EV("Event","Route 7 event",bw.EventWork.GetWorkRoamer(),choices:[new("0","Not happened"),new("1","Go to Route 7"),new("3","Finished")])};for(int i=0;i<2;i++){int current=bw.Encount.GetRoamerState(i);fields.Add(EV("Roamer"+i,i==0?"Thundurus":"Tornadus",current,choices:new[]{new Choice("0","Not roamed"),new("1","Roaming"),new("2","Defeated"),new("3","Captured")}.Where(c=>c.value==current.ToString()||c.value is "2" or "3").ToArray()));}Add("Adventure",ER("events","Roaming legends & Liberty Island",fields.ToArray(),"Changing an active roamer to defeated or captured clears its active encounter record."));Add("Adventure",ER("forestcity","Black City / White Forest",[],"Import or export the local residents’ .fc5 record.") with {fileExtension="fc5"});}
        if(s is SAV5B2W2 b){Add("Adventure",ER("keys","Key System",Enumerable.Range(0,5).SelectMany(i=>new[]{EV("Obtained"+i,Label(((KeyType5)i).ToString())+" · obtained",b.Keys.GetIsKeyObtained((KeyType5)i)),EV("Unlocked"+i,Label(((KeyType5)i).ToString())+" · unlocked",b.Keys.GetIsKeyUnlocked((KeyType5)i))}).ToArray(),actions:[new("keysAll","Give All Keys")]));}
        var link=s.Entralink;var linkFields=new List<ExtraValue>{EP(link,"WhiteForestLevel","White Entree level",999),EP(link,"BlackCityLevel","Black Entree level",999)};
        if(link is Entralink5B2W2 pass)for(int i=1;i<=3;i++)linkFields.Add(EP(pass,"PassPower"+i,"Pass Power "+i,choices:ExtraEnums<PassPower5>()));else linkFields.Add(EP(link,"MissionsComplete","Missions completed",255));
        Add("Entralink",ER("entralink","Entree & Pass Powers",linkFields.ToArray()));
        if(s is SAV5B2W2 fest){var f=fest.Festa;Add("Funfest",ER("festa","Funfest records",[EP(f,"Hosted",max:9999),EP(f,"Participated",max:9999),EP(f,"Completed",max:9999),EP(f,"TopScores","Top scores",9999),EP(f,"WhiteEXP","White experience",255),EP(f,"BlackEXP","Black experience",255),EP(f,"Participants",max:255)],actions:[new("missionsAll","Unlock All Missions")]));for(int i=0;i<=FestaBlock5.MaxMissionIndex;i++){var score=f.GetMissionRecord(i);Add("Funfest",ER("mission:"+i,Label(((Funfest5Mission)i).ToString()),[EV("Total","Best total",score.Total,9999),EV("Score","Best score",score.Score,9999),EV("Level","Difficulty",score.Level,choices:[new("0","Level 1"),new("1","Level 2 +"),new("2","Level 3 ++"),new("3","Level 3 +++"),new("7","None")]),EV("IsNew","New record",score.IsNew)],f.IsFunfestMissionUnlocked(i)?"Unlocked":"Locked",actions:i>0?[new("missionUnlock","Unlock Mission")]:[]));}}
        var forest=s.EntreeForest;forest.StartAccess();Add("Entrée Forest",ER("forest","Forest clearings",[EV("Areas","Regular areas unlocked",forest.Unlock38Areas+2,8,2),EP(forest,"Unlock9thArea","Ninth area unlocked")],"530 visitor slots, grouped by clearing.",actions:[new("forestUnlock","Unlock All Areas"),new("forestRandom","Fill with Dream World Pokémon"),new("forestClear","Empty Forest")]));
        var slots=forest.Slots;for(int i=0;i<slots.Length;i++){var slot=slots[i];string id="forest:"+i;ExtraValue[] fields=id==detailId?[EP(slot,"Species",choices:SpeciesChoices(649)),EP(slot,"Form",max:63),EP(slot,"Gender",choices:[new("0","Male"),new("1","Female"),new("2","Genderless")]),EP(slot,"Move","Special move",choices:Enumerable.Range(0,560).Select(n=>new Choice(n.ToString(),strings.movelist[n])).ToArray()),EP(slot,"Animation","Movement",choices:ExtraEnums<EntreeForestAnimation>())]:[];Add("Entrée Forest",ER(id,$"{i+1:000} · "+(slot.Species==0?"Empty":Species(slot.Species)),fields,Label(slot.Area.ToString()),SpriteFor(slot.Species,slot.Form,slot.Gender,0,s.Context),[new("forestDelete","Clear Visitor")]));}
        var subway=s.BattleSubway;Add("Battle Subway",ER("subway","Subway unlocks",new[]{EP(subway,"BP","Battle Points",65535)}.Concat(new[]{"Flag0","Flag1","Flag2","Flag3","SuperSingle","SuperDouble","SuperMulti","Flag7","NPCMet"}.Select(p=>EP(subway,p))).ToArray(),"Numbered flags retain the game’s stored names; each is edited independently."));Add("Battle Subway",ER("subwayPlay","Active challenge",[EP(s.BattleSubwayPlay,"CurrentType","Challenge type",255),EP(s.BattleSubwayPlay,"CurrentBattle","Battle number",255)]));
        foreach(string mode in SubwayModes5){int past=(int)subway.GetType().GetProperty(mode+"Past")!.GetValue(subway)!,set=(int)subway.GetType().GetProperty(mode+"Set")!.GetValue(subway)!;Add("Battle Subway",ER("subway:"+mode,Label(mode),[EP(subway,mode+"Past","Current / previous wins",65535),EP(subway,mode+"Record","Record wins",65535),EV("Continue","Continue current run",set==past/7+1)]));}
        var props=Util.GetStringList("props","en");Add("Musical",ER("props","Dress-up props",props.Select((n,i)=>EV(i.ToString(),n,s.Musical.GetHasProp(i))).ToArray(),actions:[new("propsAll","Give All Props")]));
        var records=s.Records;for(int i=0;i<Record5.Record32;i++)Add("Records",ER("record32:"+i,$"32-bit record {i}",[EV("Value","Value",records.GetRecord32(i),Record5.GetMax32(i))]));for(int i=0;i<Record5.Record16;i++)Add("Records",ER("record16:"+i,$"16-bit record {i}",[EV("Value","Value",records.GetRecord16(i),Record5.GetMax16(i))]));
        return new(tool.id,revision,tool,rows.ToArray(),[],s is SAV5BW);
    }
    void EditMisc5(JsonElement r,string id,string mode,Dictionary<string,string> edits){
        var s=(SAV5)RequireSave();if(mode=="import"&&(id!="forestcity"||s is not SAV5BW))throw new Exception("Choose the Black City / White Forest file entry.");var parts=id.Split(':');int index=parts.Length>1&&int.TryParse(parts[1],out int i)?i:-1;
        if(id=="fly"){int offset=FlyOffset5(s);foreach(int f in FlyFlags5(s)){if(mode!="flyAll"&&!edits.ContainsKey(f.ToString()))continue;bool on=mode=="flyAll"||bool.Parse(edits[f.ToString()]);int o=offset+(f>>3),mask=1<<(f&7);s.Data[o]=(byte)((s.Data[o]&~mask)|(on?mask:0));}return;}
        if(id=="events"){var bw=(SAV5BW)s;foreach(var(k,v) in edits)if(k=="Event")bw.EventWork.SetWorkRoamer(ushort.Parse(v));else if(k.StartsWith("Roamer")){int n=int.Parse(k[6..]);byte old=bw.Encount.GetRoamerState(n),next=byte.Parse(v);if(old==next)continue;bw.Encount.SetRoamerState(n,next);if(old==1){(n==0?bw.Encount.Roamer1:bw.Encount.Roamer2).Clear();bw.Encount.SetRoamerState2C(n,0);}}else bw.Misc.IsLibertyTicketActivated=bool.Parse(v);return;}
        if(id=="forestcity"&&mode=="import"){ReadExtraBytes(S(r,"path"),WhiteBlack5BW.ForestCitySize).CopyTo(((SAV5BW)s).Forest.ForestCity);return;}
        if(id=="keys"){var keys=((SAV5B2W2)s).Keys;if(mode=="keysAll"){for(int n=0;n<5;n++){keys.SetIsKeyObtained((KeyType5)n,true);keys.SetIsKeyUnlocked((KeyType5)n,true);}}else foreach(var(k,v) in edits)if(k.StartsWith("Obtained"))keys.SetIsKeyObtained((KeyType5)int.Parse(k[8..]),bool.Parse(v));else keys.SetIsKeyUnlocked((KeyType5)int.Parse(k[8..]),bool.Parse(v));return;}
        if(id=="entralink"){SetExtraProperties(s.Entralink,edits);return;}
        if(id=="festa"){var f=((SAV5B2W2)s).Festa;if(mode=="missionsAll")for(int n=1;n<=FestaBlock5.MaxMissionIndex;n++)f.UnlockFunfestMission(n);else SetExtraProperties(f,edits);return;}
        if(parts[0]=="mission"){var f=((SAV5B2W2)s).Festa;if(mode=="missionUnlock"){f.UnlockFunfestMission(index);return;}var v=f.GetMissionRecord(index);foreach(var(k,value) in edits)switch(k){case "Total":v.Total=int.Parse(value);break;case "Score":v.Score=int.Parse(value);break;case "Level":v.Level=int.Parse(value);break;case "IsNew":v.IsNew=bool.Parse(value);break;}f.SetMissionRecord(index,v);return;}
        if(parts[0]=="forest"){var f=s.EntreeForest;f.StartAccess();try{if(mode=="forestUnlock")f.UnlockAllAreas();else if(mode=="forestClear")f.DeleteAll();else if(mode=="forestRandom"){var pool=(s is SAV5BW?Encounters5BW.DreamWorld_BW:Encounters5B2W2.DreamWorld_B2W2).Concat(Encounters5DR.DreamWorld_Common).ToList();var slots=f.Slots;if(pool.Count<slots.Length)throw new Exception("The encounter collection is too small to fill this forest.");foreach(var slot in slots){int n=Util.Rand.Next(pool.Count);var encounter=pool[n];pool.RemoveAt(n);slot.Species=encounter.Species;slot.Form=encounter.Form;slot.Gender=!((IFixedGender)encounter).IsFixedGender?PersonalTable.B2W2[encounter.Species].RandomGender():encounter.Gender;ReadOnlySpan<ushort> moves=encounter.Moves;int count=moves.Length-moves.Count<ushort>(0);slot.Move=count==0?(ushort)0:moves[Util.Rand.Next(count)];}f.UnlockAllAreas();}else if(id=="forest"){foreach(var(k,v) in edits)if(k=="Areas")f.Unlock38Areas=int.Parse(v)-2;else f.Unlock9thArea=bool.Parse(v);}else if(mode=="forestDelete")f.Slots[index].Delete();else SetExtraProperties(f.Slots[index],edits);}finally{f.EndAccess();}return;}
        if(id=="subway"){SetExtraProperties(s.BattleSubway,edits);return;}if(id=="subwayPlay"){SetExtraProperties(s.BattleSubwayPlay,edits);return;}
        if(parts[0]=="subway"){var sw=s.BattleSubway;string name=parts[1];int Past()=>(int)sw.GetType().GetProperty(name+"Past")!.GetValue(sw)!;bool active=edits.TryGetValue("Continue",out var v)?bool.Parse(v):(int)sw.GetType().GetProperty(name+"Set")!.GetValue(sw)! == Past()/7+1;foreach(var(k,value) in edits)if(k!="Continue")SetProperty(sw,k,value);SetProperty(sw,name+"Set",(active?Past()/7+1:0).ToString());return;}
        if(id=="props"){if(mode=="propsAll")for(int n=0;n<Util.GetStringList("props","en").Length;n++)s.Musical.SetHasProp(n,true);else foreach(var(k,v) in edits)s.Musical.SetHasProp(int.Parse(k),bool.Parse(v));return;}
        if(parts[0] is "record32" or "record16"){var records=s.Records;try{if(parts[0]=="record32")records.SetRecord32(index,uint.Parse(edits["Value"]));else records.SetRecord16(index,ushort.Parse(edits["Value"]));}finally{records.EndAccess();}return;}
        throw new Exception("Choose an editable Unova record.");
    }
}
