using System.Reflection;
using System.Text.Json;
using PKHeX.Core;
var type=Assembly.Load("PKHeXBridge").GetType("EditorSession")!;
var saveField=type.GetField("save",BindingFlags.Instance|BindingFlags.NonPublic)!;int checks=0;
object Session(SaveFile save){var s=Activator.CreateInstance(type,new object[]{null!})!;saveField.SetValue(s,save);return s;}
SaveFile Save(object s)=>(SaveFile)saveField.GetValue(s)!;
JsonElement Req(object s,object r){using var doc=JsonDocument.Parse(JsonSerializer.Serialize(r));checks++;try{return JsonSerializer.SerializeToElement(type.GetMethod("Handle")!.Invoke(s,new object[]{doc.RootElement})!);}catch(TargetInvocationException e){System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(e.InnerException!).Throw();throw;}}
int Rev(object s)=>Req(s,new{op="state"}).GetProperty("revision").GetInt32();
void Edit(object s,string kind,string id,params (string field,string value)[] values)=>Req(s,new{op="extraSet",kind,id,revision=Rev(s),edits=values.Select(v=>new{v.field,v.value})});
void Act(object s,string kind,string id,string mode)=>Req(s,new{op="extraSet",kind,id,mode,revision=Rev(s)});
JsonElement Row(object s,string kind,string id)=>Req(s,new{op="extraEntry",kind,id});
string Value(object s,string kind,string id,string key)=>Row(s,kind,id).GetProperty("fields").EnumerateArray().Single(f=>f.GetProperty("id").GetString()==key).GetProperty("value").GetString()!;
void Assert(bool ok,string why){checks++;if(!ok)throw new Exception(why);}
void Reject(Action call,string why){try{call();}catch{checks++;return;}throw new Exception("Expected rejection: "+why);}
byte[] GBA(){var data=new byte[0x20000];for(int i=0;i<28;i++){System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(data.AsSpan(i*0x1000+0xFF4),(short)(i%14));System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(data.AsSpan(i*0x1000+0xFF8),0x08012025);if(i%14==0)data.AsSpan(i*0x1000,8).Fill(255);}return data;}
SaveFile Fixture(GameVersion game)=>game switch {GameVersion.R or GameVersion.S=>new SAV3RS(GBA()){Version=game,Language=2},GameVersion.E=>new SAV3E(GBA()){Language=2},GameVersion.FR or GameVersion.LG=>new SAV3FRLG(GBA()){Version=game,Language=2},GameVersion.D or GameVersion.P=>new SAV4DP(new byte[0x80000]){Version=game},GameVersion.Pt=>new SAV4Pt(new byte[0x80000]),GameVersion.HG or GameVersion.SS=>new SAV4HGSS(new byte[0x80000]){Version=game},_=>BlankSaveFile.Get(game,"Parity")};
SaveFile ReadSave(SaveFile source,byte[] data)=>source switch {SAV2=>new SAV2(data,(LanguageID)source.Language,source.Version),SAV3RS=>new SAV3RS(data){Version=source.Version,Language=source.Language},SAV3E=>new SAV3E(data),SAV3FRLG=>new SAV3FRLG(data){Version=source.Version,Language=source.Language},SAV4DP=>new SAV4DP(data),SAV4Pt=>new SAV4Pt(data),SAV4HGSS=>new SAV4HGSS(data),SAV5BW=>new SAV5BW(data),SAV5B2W2=>new SAV5B2W2(data),SAV6XY=>new SAV6XY(data),SAV6AO=>new SAV6AO(data),SAV7SM=>new SAV7SM(data),SAV7USUM=>new SAV7USUM(data),SAV7b=>new SAV7b(data),_=>SaveUtil.GetSaveFile(data)!};
if(args.Contains("--samples")){foreach(var game in new[]{"GD","E","FR","D","Pt","HG","B","B2","BD"}){var session=Session(Fixture(GameVersion.BD));Req(session,new{op="demo",version=game});foreach(var tool in Req(session,new{op="extraTools"}).EnumerateArray()){string kind=tool.GetProperty("id").GetString()!;if(new[]{"misc3","misc4","misc5","mail","unlocks8b"}.Contains(kind)){Console.WriteLine(game+"/"+kind);Req(session,new{op="extraPage",kind});}}}Console.WriteLine("PASS sample tool read checks");return;}
if(args.Contains("--events")) {
 var scratch=Path.Combine(Environment.CurrentDirectory,"work/tests/events028");Directory.CreateDirectory(scratch);
 string Rows(object session)=>Req(session,new{op="eventResearch"}).GetProperty("entries").ToString();
 foreach(var game in new[]{GameVersion.GD,GameVersion.SI,GameVersion.C,GameVersion.R,GameVersion.S,GameVersion.E,GameVersion.FR,GameVersion.LG,GameVersion.D,GameVersion.P,GameVersion.Pt,GameVersion.HG,GameVersion.SS,GameVersion.B,GameVersion.W,GameVersion.B2,GameVersion.W2,GameVersion.X,GameVersion.Y,GameVersion.OR,GameVersion.AS,GameVersion.SN,GameVersion.MN,GameVersion.US,GameVersion.UM,GameVersion.GP,GameVersion.GE,GameVersion.BD,GameVersion.SP}) {
  var session=Session(Fixture(game));Assert(Req(session,new{op="state"}).GetProperty("canEvents").GetBoolean(),game+" event availability");var before=Save(session).Data.ToArray();var rows=Req(session,new{op="eventResearch"}).GetProperty("entries").EnumerateArray().ToArray();Assert(before.SequenceEqual(Save(session).Data.ToArray()),game+" event read purity");Assert(rows.Length>0,"Rows exist");Assert(rows.Select(x=>x.GetProperty("id").GetString()).Distinct().Count()==rows.Length,"Unique event IDs");
  var chosen=rows.GroupBy(x=>x.GetProperty("section").GetString()).SelectMany(g=>new[]{g.First(),g.Last(),g.FirstOrDefault(x=>x.GetProperty("named").GetBoolean())}).Where(x=>x.ValueKind!=JsonValueKind.Undefined).Concat(rows.Where(x=>x.GetProperty("choices").GetArrayLength()>0).Take(3)).DistinctBy(x=>x.GetProperty("id").GetString()).ToArray();
  foreach(var row in chosen){string id=row.GetProperty("id").GetString()!,kind=row.GetProperty("kind").GetString()!,value=kind=="bool"?(row.GetProperty("value").GetString()=="true"?"false":"true"):kind=="Int32"?"-123":"123";if(row.GetProperty("choices").GetArrayLength()>0)value=row.GetProperty("choices")[0].GetProperty("value").GetString()!;var previous=Rows(session);Req(session,new{op="eventResearchSet",id,value,revision=Rev(session)});Assert(Req(session,new{op="eventResearch"}).GetProperty("entries").EnumerateArray().Single(x=>x.GetProperty("id").GetString()==id).GetProperty("value").GetString()==value,"Event readback");var after=Rows(session);Req(session,new{op="undo"});Assert(Rows(session)==previous,"Event Undo");Req(session,new{op="redo"});Assert(Rows(session)==after,"Event Redo");}
  before=Save(session).Write().ToArray();Reject(()=>Req(session,new{op="eventResearchSet",id="Flags:-1",value="true",revision=Rev(session)}),"Event bounds");Reject(()=>Req(session,new{op="eventResearchSet",id=chosen[0].GetProperty("id").GetString(),value="true",revision=Rev(session)-1}),"Stale event revision");Reject(()=>Req(session,new{op="eventResearchSet",id="Flags:0",value="not-bool",revision=Rev(session)}),"Bool validation");if(rows.Any(x=>x.GetProperty("section").GetString()=="Variables"))Reject(()=>Req(session,new{op="eventResearchSet",id="Variables:0",value="99999999999999999",revision=Rev(session)}),"Variable overflow");Assert(before.SequenceEqual(Save(session).Write().ToArray()),"Rejected event edits atomic");
  var expected=Rows(session);saveField.SetValue(session,ReadSave(Save(session),Save(session).Write().ToArray()));Assert(Save(session).ChecksumsValid,"Event serialized checksums");Assert(Rows(session)==expected,"Event serialized values");
  Console.WriteLine($"PASS {game}: {rows.Count(x=>x.GetProperty("named").GetBoolean())} researched labels, {rows.Length} records, bounds, typed changes, Undo/Redo and saved readback");
 }
 foreach(var game in new[]{GameVersion.B2,GameVersion.X,GameVersion.GP,GameVersion.BD}) {
  var fixture=Fixture(game);if(fixture is SAV6)System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(fixture.Data[^0x1F0..],0x42454546);if(fixture is SAV7b){System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(fixture.Data[(0xB8800-0x1F0)..],0x42454546);System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(fixture.Data[(0xB8800-0x200+0xB0)..],0x13);}var session=Session(fixture);string input=Path.Combine(scratch,game+"-before.sav"),output=Path.Combine(scratch,game+"-after.sav"),report=Path.Combine(scratch,game+"-report.txt");File.WriteAllBytes(input,Save(session).Write().ToArray());var first=Req(session,new{op="eventResearch"}).GetProperty("entries").EnumerateArray().First(x=>x.GetProperty("kind").GetString()=="bool");Req(session,new{op="eventResearchSet",id=first.GetProperty("id").GetString(),value=first.GetProperty("value").GetString()=="true"?"false":"true",revision=Rev(session)});File.WriteAllBytes(output,Save(session).Write().ToArray());var original=Save(session).Write().ToArray();int revision=Rev(session);var diff=Req(session,new{op="eventCompare",previous=input});Assert(diff.GetProperty("entries").GetArrayLength()==1,"Current workspace diff count");var two=Req(session,new{op="eventCompare",previous=input,updated=output});Assert(two.GetProperty("entries").ToString()==diff.GetProperty("entries").ToString(),"Two-file comparison");Assert(Rev(session)==revision&&original.SequenceEqual(Save(session).Write().ToArray()),"Compare never mutates");Req(session,new{op="eventCompareExport",token=two.GetProperty("token").GetString(),path=report});Assert(File.ReadAllText(report)==two.GetProperty("report").GetString(),"Report exact");Reject(()=>Req(session,new{op="eventCompareExport",token=two.GetProperty("token").GetString(),path=input}),"Cannot overwrite comparison input");Reject(()=>Req(session,new{op="eventCompareExport",token=diff.GetProperty("token").GetString(),path=report}),"Expired comparison token");var reverse=Req(session,new{op="eventCompare",previous=output,updated=input});Assert(reverse.GetProperty("entries")[0].GetProperty("before").GetString()==two.GetProperty("entries")[0].GetProperty("after").GetString(),"Diff direction");var equal=Req(session,new{op="eventCompare",previous=input,updated=input});Assert(equal.GetProperty("entries").GetArrayLength()==0,"Identical saves");Console.WriteLine("PASS "+game+" comparison, report export, source protection and snapshot purity");
 }
 var mismatch=Session(Fixture(GameVersion.BD));Reject(()=>Req(mismatch,new{op="eventCompare",previous=Path.Combine(scratch,"X-before.sav")}),"Mismatched family");Console.WriteLine($"PASS {checks} event requests/assertions");return;
}
if(args.Contains("--edges")) {
 foreach(var game in new[]{GameVersion.Pt,GameVersion.HG}) {
  var sav=(SAV4)Fixture(game);var blocks=(IReadOnlyList<BlockInfo4>)typeof(SAV4).GetProperty("ExtraBlocks",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(sav)!;var b=blocks[1];
  var hall=new Hall4(sav.Buffer.Slice(b.Offset,Hall4.SIZE_USED)){Key=0,Magic=0x20060623,Revision=7,BlockSize=Hall4.SIZE_USED-16,BlockID=(ushort)b.ID};hall.SetCount(0,24,77);hall.RefreshChecksum();Assert(sav.GetHall()!=null,"Initialized Hall discoverable");
  var session=Session(sav);var before=sav.Write().ToArray();Edit(session,"misc4","hall:25",("0","123"),("1","456"),("2","789"));Assert(((SAV4)Save(session)).GetHall()!.ChecksumValid,"Hall checksum refreshed");Assert(((SAV4)Save(session)).GetHall()!.GetCount(0,24)==77,"Hall neighbor preserved");
  saveField.SetValue(session,ReadSave(Save(session),Save(session).Write().ToArray()));Assert(Save(session).ChecksumsValid,"Hall save checksums");foreach(var (key,value) in new[]{("0","123"),("1","456"),("2","789")})Assert(Value(session,"misc4","hall:25",key)==value,"Hall serialized values");Req(session,new{op="undo"});Assert(before.SequenceEqual(Save(session).Write().ToArray()),"Hall Undo bytes");Console.WriteLine("PASS "+game+" initialized Hall block, checksum, neighbors, saved readback and Undo");
 }
 var scratch=Path.Combine(Path.GetTempPath(),"keepsake-028-edges-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(scratch);
 try {foreach(var game in new[]{GameVersion.B,GameVersion.W}) {
  var session=Session(Fixture(game));var before=Save(session).Write().ToArray();var bytes=Enumerable.Range(0,WhiteBlack5BW.ForestCitySize).Select(i=>(byte)(i%251)).ToArray();string input=Path.Combine(scratch,"input.fc5"),output=Path.Combine(scratch,"output.fc5");File.WriteAllBytes(input,bytes);
  Req(session,new{op="extraSet",kind="misc5",id="forestcity",mode="import",revision=Rev(session),path=input});Req(session,new{op="extraExport",kind="misc5",id="forestcity",path=output});Assert(File.ReadAllBytes(output).SequenceEqual(bytes),"FC5 exact export");saveField.SetValue(session,ReadSave(Save(session),Save(session).Write().ToArray()));Assert(Save(session).ChecksumsValid&&((SAV5BW)Save(session)).Forest.ForestCity.Span.SequenceEqual(bytes),"FC5 save readback");
  var after=Save(session).Write().ToArray();File.WriteAllBytes(input,[1,2]);Reject(()=>Req(session,new{op="extraSet",kind="misc5",id="forestcity",mode="import",revision=Rev(session),path=input}),"FC5 bad size");Reject(()=>Req(session,new{op="extraSet",kind="misc5",id="fly",mode="import",revision=Rev(session),path=input}),"FC5 wrong entry");Assert(after.SequenceEqual(Save(session).Write().ToArray()),"FC5 rejection atomic");Req(session,new{op="undo"});Assert(before.SequenceEqual(Save(session).Write().ToArray()),"FC5 Undo");Console.WriteLine("PASS "+game+" residents file, bounds, destination guard, saved readback and Undo");
 }} finally {Directory.Delete(scratch,true);}
 foreach(var game in new[]{GameVersion.BD,GameVersion.SP}) foreach(var id in new[]{"spiritomb","darkrai","shaymin","arceus","legend","roamers"}) {
  var sav=(SAV8BS)Fixture(game);sav.FlagWork.SetFlag(308,true);sav.FlagWork.SetWork(84,4);sav.Encounter.Roamer1Encount=3;sav.Encounter.Roamer2Encount=2;var session=Session(sav);var before=sav.Write().ToArray();Assert(Row(session,"unlocks8b",id).GetProperty("actions").GetArrayLength()==1,"Encounter ready");Act(session,"unlocks8b",id,id);
  Assert(Row(session,"unlocks8b",id).GetProperty("actions").GetArrayLength()==0,"Encounter no longer pending");saveField.SetValue(session,ReadSave(Save(session),Save(session).Write().ToArray()));Assert(Save(session).ChecksumsValid,"Event checksum");Assert(Row(session,"unlocks8b",id).GetProperty("actions").GetArrayLength()==0,"Event serialized");Req(session,new{op="undo"});Assert(before.SequenceEqual(Save(session).Write().ToArray()),"Event Undo");Console.WriteLine("PASS "+game+" "+id+" readiness, saved readback and Undo");
 }
 Console.WriteLine($"PASS {checks} edge requests/assertions");return;
}
if(!args.Contains("--advanced"))foreach(var game in new[]{GameVersion.R,GameVersion.S,GameVersion.E,GameVersion.FR,GameVersion.LG,GameVersion.D,GameVersion.P,GameVersion.Pt,GameVersion.HG,GameVersion.SS,GameVersion.B,GameVersion.W,GameVersion.B2,GameVersion.W2}){
 var session=Session(Fixture(game));string kind=Save(session).Generation switch {3=>"misc3",4=>"misc4",_=>"misc5"};
 var before=Save(session).Data.ToArray();var page=Req(session,new{op="extraPage",kind});Assert(before.SequenceEqual(Save(session).Data.ToArray()),game+" read purity");var rows=page.GetProperty("entries").EnumerateArray().ToArray();Assert(rows.Select(r=>r.GetProperty("id").GetString()).Distinct().Count()==rows.Length,"Unique row IDs");
 foreach(var row in rows){string id=row.GetProperty("id").GetString()!;if(id.StartsWith("forest:")&&id!="forest:0"&&id!="forest:529")continue;var fields=Row(session,kind,id).GetProperty("fields").EnumerateArray().ToArray();var changes=new List<(string field,string value)>();
 foreach(var f in fields){string key=f.GetProperty("id").GetString()!,current=f.GetProperty("value").GetString()!,fieldKind=f.GetProperty("kind").GetString()!;if(kind=="misc3"&&id=="record:1"&&key=="Value")continue;if(id.StartsWith("painting:")&&key=="Enabled") {changes.Add((key,"true"));continue;}string next=fieldKind switch {"bool"=>current=="true"?"false":"true","enum"=>f.GetProperty("choices").EnumerateArray().FirstOrDefault(x=>x.GetProperty("value").GetString()!=current).TryGetProperty("value",out var c)?c.GetString()!:current,"text"=>"Test","dotart"=>string.Concat(Enumerable.Range(0,480).Select(i=>(i%4).ToString())),_=>Math.Clamp(17,decimal.Parse(f.GetProperty("min").GetString()!),decimal.Parse(f.GetProperty("max").GetString()!)).ToString()};if(id=="backdrops")next=key;if(id.StartsWith("painting:")&&key=="Caption")next="1";changes.Add((key,next));}
 if(changes.Count==0)continue;try {Edit(session,kind,id,changes.ToArray());foreach(var c in changes)Assert(Value(session,kind,id,c.field)==c.value,$"{game}/{id}/{c.field}: expected {c.value}, got {Value(session,kind,id,c.field)}");}catch(Exception e){throw new Exception($"{game}/{kind}/{id}: {e.Message}",e);}
 }
 before=Save(session).Write().ToArray();Reject(()=>Edit(session,kind,rows[0].GetProperty("id").GetString()!, ("Invalid","1")),"Unknown field");Assert(before.SequenceEqual(Save(session).Write().ToArray()),"Atomic invalid edit");
 var expected=Req(session,new{op="extraPage",kind}).ToString();var data=Save(session).Write().ToArray();var copy=ReadSave(Save(session),data);Assert(copy.ChecksumsValid,game+" checksum");saveField.SetValue(session,copy);Assert(Req(session,new{op="extraPage",kind}).ToString()==expected,game+" full page persisted");
 Console.WriteLine($"PASS {game}: {rows.Length} records, field readback, read purity, validation, checksummed serialization");
}

if(args.Contains("--fields")){Console.WriteLine($"PASS {checks} checks");return;}
string Entries(object session,string kind)=>Req(session,new{op="extraPage",kind}).GetProperty("entries").ToString();
foreach(var game in new[]{GameVersion.E,GameVersion.Pt,GameVersion.HG,GameVersion.B,GameVersion.B2}){
 var session=Session(Fixture(game));string kind=Save(session).Generation switch{3=>"misc3",4=>"misc4",_=>"misc5"};var rows=Req(session,new{op="extraPage",kind}).GetProperty("entries").EnumerateArray().ToArray();
 foreach(var row in rows){string id=row.GetProperty("id").GetString()!;if(id.StartsWith("forest:")&&id!="forest:529")continue;foreach(var action in row.GetProperty("actions").EnumerateArray()){string mode=action.GetProperty("value").GetString()!;var before=Entries(session,kind);try{Act(session,kind,id,mode);Req(session,new{op="undo"});Assert(Entries(session,kind)==before,$"{game}/{id}/{mode} Undo");Req(session,new{op="redo"});}catch(Exception e){throw new Exception($"{game}/{id}/{mode}: {e.Message}",e);}}}
 if(Save(session) is SAV5 s5){Edit(session,kind,"subway",("Flag3","true"),("Flag7","false"));Assert(s5.BattleSubway.Flag3&&!s5.BattleSubway.Flag7,"Subway flags independent");Edit(session,kind,"subway:Single",("SinglePast","21"),("Continue","true"));Assert(((SAV5)Save(session)).BattleSubway.SingleSet==4,"Subway set number");Edit(session,kind,"subway:Single",("SinglePast","28"));Assert(((SAV5)Save(session)).BattleSubway.SingleSet==5,"Subway continuation survives changed wins");var before=Save(session).Write().ToArray();Reject(()=>Edit(session,kind,"forest:0",("Species","25"),("Form","64")),"Forest packed overflow");Assert(before.SequenceEqual(Save(session).Write().ToArray()),"Forest atomic validation");}
 if(game==GameVersion.B2){var flySave=(SAV5)Save(session);int offset=0x20392+8;flySave.Data[offset]=0xB9;Act(session,kind,"fly","flyAll");Assert(flySave.Data[offset]==0xBD,"Fly flag 66 preserves other bits");}
 if(game==GameVersion.Pt){var s4=(SAV4Pt)Save(session);s4.General[0x696C+16]=0xCA;s4.General[0x696C+17]=0xFE;Edit(session,kind,"frontier:3:0:0",("Rank2","2"));Assert(s4.General[0x696C+16]==0xCA&&s4.General[0x696C+17]==0xFE,"Castle 16-bit rank preserves adjacent mode");Edit(session,kind,"dotart",("Pixels",new string('3',480)));Assert(s4.GetPoketchDotArtistData().All(b=>b==255),"480 packed pixels");var before=s4.Write().ToArray();Reject(()=>Edit(session,kind,"dotart",("Pixels",new string('4',480))),"Pixel shade bounds");Assert(before.SequenceEqual(Save(session).Write().ToArray()),"Invalid pixels atomic");}
 Console.WriteLine("PASS "+game+" collection bulk actions, Undo/Redo and packed-field isolation");
}
foreach(bool japanese in new[]{false,true}){
 var sav=new SAV4BR();typeof(SAV4BR).GetField("Container",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(sav,new Memory<byte>(new byte[SaveUtil.SIZE_G4BR]));sav.Language=japanese?1:2;var s=Session(sav);var page=Req(s,new{op="extraPage",kind="gear"});var rows=page.GetProperty("entries").EnumerateArray().ToArray();Assert(rows.Select(r=>r.GetProperty("id").GetString()).Distinct().Count()==rows.Length,"Unique wardrobe IDs");
 Act(s,"gear","","give");foreach(var row in rows.Where(r=>r.GetProperty("id").GetString()!.StartsWith("gear:")))Assert(Value(s,"gear",row.GetProperty("id").GetString()!,"Owned")=="true","Give gear");
 foreach(var row in rows.Where(r=>r.GetProperty("id").GetString()!.StartsWith("special:"))){var f=row.GetProperty("fields")[0];Edit(s,"gear",row.GetProperty("id").GetString()!,(f.GetProperty("id").GetString()!,"true"));}
 var expected=Entries(s,"gear");var bytes=Save(s).Write();saveField.SetValue(s,new SAV4BR(bytes));Assert(Save(s).ChecksumsValid&&Entries(s,"gear")==expected,"Gear serialized roundtrip");Act(s,"gear","","clear");Req(s,new{op="undo"});Assert(Entries(s,"gear")==expected,"Gear Undo");Console.WriteLine("PASS PBR wardrobe "+(japanese?"JP":"EN"));
}
foreach(var game in new[]{GameVersion.BD,GameVersion.SP}){
 var s=Session(Fixture(game));foreach(string id in new[]{"zones","fashion","trainers"}){var row=Row(s,"unlocks8b",id);foreach(var a in row.GetProperty("actions").EnumerateArray()){var before=Save(s).Write().ToArray();Act(s,"unlocks8b",id,a.GetProperty("value").GetString()!);Req(s,new{op="undo"});Assert(before.SequenceEqual(Save(s).Write().ToArray()),"BDSP unlock Undo");Req(s,new{op="redo"});}}
 Console.WriteLine("PASS "+game+" destination, fashion and trainer bulk changes");
}
foreach(var game in new[]{GameVersion.RD,GameVersion.GD,GameVersion.R,GameVersion.E,GameVersion.FR,GameVersion.D,GameVersion.Pt,GameVersion.HG,GameVersion.B,GameVersion.W2,GameVersion.X,GameVersion.OR,GameVersion.SN,GameVersion.UM,GameVersion.GP,GameVersion.SW,GameVersion.BD,GameVersion.PLA,GameVersion.SL,GameVersion.VL,GameVersion.ZA}){
 var session=Session(Fixture(game));Assert(Req(session,new{op="state"}).GetProperty("canDex").GetBoolean(),game+" native dex availability");Req(session,new{op="dexSet",species=25,seen=true,caught=true});Assert(Save(session).GetCaught(25)&&Save(session).GetSeen(25),game+" basic flags persist");Req(session,new{op="dexSet",species=25,seen=false,caught=false});Assert(!Save(session).GetCaught(25)&&!Save(session).GetSeen(25),game+" basic flags clear");var options=Req(session,new{op="dexBulkOptions"});var actions=options.GetProperty("actions").EnumerateArray().Select(a=>a.GetProperty("value").GetString()!).ToArray();
 foreach(var action in actions){var before=Save(session).Write().ToArray();Req(session,new{op="dexBulk",revision=Rev(session),action,shiny=true,allLanguages=true});var after=Save(session).Write().ToArray();Req(session,new{op="undo"});Assert(before.SequenceEqual(Save(session).Write().ToArray()),game+" dex Undo "+action);Req(session,new{op="redo"});Assert(after.SequenceEqual(Save(session).Write().ToArray()),game+" dex Redo "+action);}
 var prior=Save(session).Write().ToArray();Reject(()=>Req(session,new{op="dexBulk",revision=Rev(session)-1,action="seen"}),"Stale Dex revision");Reject(()=>Req(session,new{op="dexBulk",revision=Rev(session),action="notAnAction"}),"Unknown Dex action");Assert(prior.SequenceEqual(Save(session).Write().ToArray()),"Dex rejected atomically");
 if(options.GetProperty("entries").GetBoolean()){Req(session,new{op="dexBulk",revision=Rev(session),action="complete",species=25,shiny=true,allLanguages=true});Assert(Save(session).GetCaught(25),"Single entry complete");Req(session,new{op="dexBulk",revision=Rev(session),action="unseen",species=25});Assert(!Save(session).GetSeen(25),"Single entry clear");}
 Console.WriteLine("PASS "+game+" Pokédex bulk actions, shiny/language options, entry scope, Undo/Redo and revision guards");
}
Console.WriteLine($"PASS {checks} checks");
