using System.Reflection;
using System.Text.Json;
using PKHeX.Core;
var type=Assembly.Load("PKHeXBridge").GetType("EditorSession")!;
var saveField=type.GetField("save",BindingFlags.Instance|BindingFlags.NonPublic)!;
var entityField=type.GetField("entity",BindingFlags.Instance|BindingFlags.NonPublic)!;
int checks=0;string scratch=Path.Combine(Path.GetTempPath(),"keepsake023-"+Guid.NewGuid());Directory.CreateDirectory(scratch);
object Session(SaveFile save){var s=Activator.CreateInstance(type,new object[]{null!})!;saveField.SetValue(s,save);return s;}
SaveFile Current(object s)=>(SaveFile)saveField.GetValue(s)!;
JsonElement Req(object s,object r){using var doc=JsonDocument.Parse(JsonSerializer.Serialize(r));checks++;try{return JsonSerializer.SerializeToElement(type.GetMethod("Handle")!.Invoke(s,new object[]{doc.RootElement})!);}catch(TargetInvocationException e){System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(e.InnerException!).Throw();throw;}}
int Rev(object s)=>Req(s,new{op="state"}).GetProperty("revision").GetInt32();
void Edit(object s,string kind,string id,params (string field,string value)[] values)=>Req(s,new{op="extraSet",kind,id,revision=Rev(s),edits=values.Select(v=>new{v.field,v.value})});
void Act(object s,string kind,string id,string mode)=>Req(s,new{op="extraSet",kind,id,mode,revision=Rev(s)});
JsonElement Row(object s,string kind,string id)=>Req(s,new{op="extraEntry",kind,id});
string Value(object s,string kind,string id,string field)=>Row(s,kind,id).GetProperty("fields").EnumerateArray().Single(f=>f.GetProperty("id").GetString()==field).GetProperty("value").GetString()!;
void Assert(bool pass,string why){checks++;if(!pass)throw new Exception(why);}
void Reject(Action call,string why){try{call();}catch{checks++;return;}throw new Exception("Expected rejection: "+why);}
string Export(object s,string kind,string id,bool decrypted=false){string file=Path.Combine(scratch,Guid.NewGuid()+".bin");Req(s,new{op="extraExport",kind,id,path=file,decrypted});return file;}
void Import(object s,string kind,string id,string path)=>Req(s,new{op="extraSet",kind,id,mode="import",path,revision=Rev(s)});
void Roundtrip(object s,Func<byte[],SaveFile> parse,string kind,string id){var expected=Row(s,kind,id).ToString();var copy=parse(Current(s).Write().ToArray());Assert(copy.ChecksumsValid,kind+" checksums");saveField.SetValue(s,copy);Assert(Row(s,kind,id).ToString()==expected,kind+" serialized fields");}
foreach(var game in new[]{GameVersion.X,GameVersion.Y,GameVersion.OR,GameVersion.AS}){
 var s=Session(BlankSaveFile.Get(game,"Fixture"));var sav=(ISaveBlock6Main)Current(s);var before=Current(s).Data.ToArray();Assert(Req(s,new{op="extraPage",kind="link6"}).GetProperty("entries").GetArrayLength()==13,"Link rewards");Assert(before.SequenceEqual(Current(s).Data.ToArray()),"Link read purity");
 Edit(s,"link6","settings",("Origin","KeepSake delivery"),("Enabled","true"),("BattlePoints","9999"),("Pokemiles","321"));for(int i=1;i<=6;i++)Edit(s,"link6","item:"+i,("Item"+i,"1"),("Quantity"+i,"65535"));Assert(((ISaveBlock6Main)Current(s)).Link.Gifts.Quantity6==65535,"Link final item");string file=Export(s,"link6","settings");Assert(new FileInfo(file).Length==PL6.Size,"Link file size");Edit(s,"link6","settings",("Origin","Changed"));Import(s,"link6","settings",file);Assert(Value(s,"link6","settings","Origin")=="KeepSake delivery","Link import");Req(s,new{op="undo"});Assert(Value(s,"link6","settings","Origin")=="Changed","Link Undo");Req(s,new{op="redo"});Reject(()=>Edit(s,"link6","item:1",("Quantity1","65536")),"Link limit");
 Roundtrip(s,b=>game is GameVersion.X or GameVersion.Y?new SAV6XY(b):new SAV6AO(b),"link6","settings");var link=((ISaveBlock6Main)Current(s)).Link;Assert(link.Checksum==Checksums.CRC16_CCITT(link.Data[0x200..^4]),"Inner link checksum");Console.WriteLine("PASS "+game+" Pokémon Link");
}
foreach(var game in new[]{GameVersion.B,GameVersion.W,GameVersion.B2,GameVersion.W2}){
 var s=Session(BlankSaveFile.Get(game,"Fixture"));var before=Current(s).Data.ToArray();Req(s,new{op="extraPage",kind="globallink5"});Req(s,new{op="extraPage",kind="dlc5"});Assert(before.SequenceEqual(Current(s).Data.ToArray()),"Download/Global Link read purity");
 Edit(s,"globallink5","settings",("Date","2026-09-25"),("UploadCount","-1"),("IsRegistered","true"),("SelectedFurnitureIndex","127"),("IsFurnitureSynchronized","true"));for(int i=0;i<20;i++)Edit(s,"globallink5","item:"+i,("Item","1"),("Quantity","255"));for(int i=0;i<5;i++)Edit(s,"globallink5","furniture:"+i,("Name","KeepSake"),("Value","65535"));Assert(((SAV5)Current(s)).GlobalLink.UploadDate.IsValid,"Date weekday");Assert(Value(s,"globallink5","furniture:4","Name")=="KeepSake","Boxed furniture write");Edit(s,"globallink5","settings",("Date",""));Assert(((SAV5)Current(s)).GlobalLink.UploadDate.IsEmpty,"Clear date");Req(s,new{op="undo"});Reject(()=>Edit(s,"globallink5","settings",("Date","2026-02-30")),"Bad calendar date");
 var pixels=new byte[256*192*4];for(int i=0;i<pixels.Length;i+=4){pixels[i+3]=255;if(i/(256*4)<96)pixels[i+2]=255;else pixels[i]=255;}
 Req(s,new{op="cgearImageSet",revision=Rev(s),pixels=Convert.ToBase64String(pixels)});var image=Req(s,new{op="cgearImage"});Assert(!image.GetProperty("empty").GetBoolean(),"C-Gear occupied");var output=Convert.FromBase64String(image.GetProperty("pixels").GetString()!);Assert(output[2]>240&&output[0]==0&&output[(191*256*4)]>240,"C-Gear color/order");string skin=Export(s,"dlc5","cgear");var skinBefore=((SAV5)Current(s)).CGearSkinData.ToArray();Import(s,"dlc5","cgear",skin);Assert(((SAV5)Current(s)).CGearSkinData.Span.SequenceEqual(skinBefore),"Skin binary roundtrip");Req(s,new{op="undo"});
 var overflow=(byte[])pixels.Clone();for(int i=0;i<32;i++){overflow[i*4]=(byte)(i*8);overflow[i*4+1]=(byte)(i*8);overflow[i*4+2]=(byte)(i*8);}before=Current(s).Data.ToArray();Reject(()=>Req(s,new{op="cgearImageSet",revision=Rev(s),pixels=Convert.ToBase64String(overflow)}),"Too many colors");Assert(before.SequenceEqual(Current(s).Data.ToArray()),"Image rejection purity");Reject(()=>Req(s,new{op="cgearImageSet",revision=Rev(s)-1,pixels=Convert.ToBase64String(pixels)}),"Stale image");

 // Exercise the exact tile limit with deterministic, distinct two-color patterns.
 var random=new Random(23);var tiles=Enumerable.Range(0,256).Select(_=>Enumerable.Range(0,64).Select(_=>(byte)random.Next(2)).ToArray()).ToArray();
 byte[] TileImage(int unique){var image=new byte[256*192*4];for(int n=0;n<768;n++)for(int y=0;y<8;y++)for(int x=0;x<8;x++){int i=(((n/32)*8+y)*256+(n%32)*8+x)*4;byte c=(byte)(tiles[n%unique][y*8+x]*255);image[i]=image[i+1]=image[i+2]=c;image[i+3]=255;}return image;}
 Req(s,new{op="cgearImageSet",revision=Rev(s),pixels=Convert.ToBase64String(TileImage(255))});Assert(!Req(s,new{op="cgearImage"}).GetProperty("empty").GetBoolean(),"255 unique tiles accepted");Req(s,new{op="undo"});before=Current(s).Data.ToArray();Reject(()=>Req(s,new{op="cgearImageSet",revision=Rev(s),pixels=Convert.ToBase64String(TileImage(256))}),"256 unique tiles rejected");Assert(before.SequenceEqual(Current(s).Data.ToArray()),"Tile overflow atomicity");
 // Binary imports translate the layout between the two Unova game families.
 var other=Session(BlankSaveFile.Get(game is GameVersion.B or GameVersion.W?GameVersion.B2:GameVersion.B,"Other"));Import(other,"dlc5","cgear",skin);Assert(Req(other,new{op="cgearImage"}).GetProperty("pixels").GetString()==image.GetProperty("pixels").GetString(),"Cross-game skin conversion");
 var ids=Req(s,new{op="extraPage",kind="dlc5"}).GetProperty("entries").EnumerateArray().Select(r=>r.GetProperty("id").GetString()!).ToArray();
 foreach(var id in ids.Where(id=>id!="cgear")){var path=Export(s,"dlc5",id);Import(s,"dlc5",id,path);Assert(new FileInfo(Export(s,"dlc5",id)).Length==new FileInfo(path).Length,"DLC file size "+id);Req(s,new{op="undo"});}

 var videoData=new byte[BattleVideo5.SIZE];var video=new BattleVideo5(videoData){IsDecrypted=true,VideoName="KeepSake",RandomSeed=0x123456789ABCDEF0,RandomMult=LCRNG64.Mult,RandomAdd=LCRNG64.Add,EndSentinel=0xE281};video.RefreshChecksums();var videoFile=Path.Combine(scratch,"test.bv5");File.WriteAllBytes(videoFile,videoData);Import(s,"dlc5","video:0",videoFile);var videoOut=File.ReadAllBytes(Export(s,"dlc5","video:0",true));Assert(BattleVideo5.GetIsDecrypted(videoOut)&&videoOut.SequenceEqual(videoData),"Gen5 populated decrypted video roundtrip");Import(s,"dlc5","video:1",Export(s,"dlc5","video:0"));Assert(File.ReadAllBytes(Export(s,"dlc5","video:1",true)).SequenceEqual(videoData),"Gen5 populated encrypted video roundtrip");
 Edit(s,"dlc5","musical",("MusicalName","KeepSake"));Assert(Value(s,"dlc5","musical","MusicalName")=="KeepSake","Musical name");var invalid=Path.Combine(scratch,"invalid.bin");File.WriteAllBytes(invalid,[1,2,3]);before=Current(s).Data.ToArray();Reject(()=>Import(s,"dlc5","link1",invalid),"Wrong length");Assert(Current(s).Data.SequenceEqual(before),"Download import atomicity");
 Roundtrip(s,b=>game is GameVersion.B or GameVersion.W?new SAV5BW(b):new SAV5B2W2(b),"globallink5","settings");Assert(((SAV5)Current(s)).CGearSkinData.Span.SequenceEqual(skinBefore),"Serialized skin");File.WriteAllBytes(Path.Combine(scratch,game+"-fixture.sav"),Current(s).Write().ToArray());Console.WriteLine("PASS "+game+" Global Link / downloaded content / C-Gear");
}
foreach(var game in new[]{GameVersion.Pt,GameVersion.HG,GameVersion.SS}){
 SAV4 sav=game==GameVersion.Pt?new SAV4Pt(new byte[0x80000]):new SAV4HGSS(new byte[0x80000]);
 var blocks=(BlockInfo4[])typeof(SAV4).GetProperty("ExtraBlocks",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(sav)!;
 foreach(var block in blocks.Skip(2)){var video=new BattleVideo4(sav.Buffer.Slice(block.Offset,BattleVideo4.SIZE_USED)){IsDecrypted=true,Key=0,Magic=0x20060623,Revision=7,BlockSize=BattleVideo4.SIZE_USED-16,BlockID=(ushort)block.ID};video.RefreshChecksums();video.Encrypt();}
 var s=Session(sav);var before=sav.Data.ToArray();for(int i=0;i<4;i++){Row(s,"dlc4","video:"+i);Assert(Current(s).Data.SequenceEqual(before),"Video preview purity");string path=Export(s,"dlc4","video:"+i,true);var file=new BattleVideo4(File.ReadAllBytes(path)){IsDecrypted=true,Key=123456};file.RefreshChecksums();var data=file.Data.ToArray();File.WriteAllBytes(path,data);Import(s,"dlc4","video:"+i,path);var current=((SAV4)Current(s)).GetBattleVideo(i);Assert(current!=null&&current.Key==0&&current.Revision==7&&current.ChecksumValid,"Video metadata / key preservation");Req(s,new{op="undo"});Assert(Current(s).Data.SequenceEqual(before),"Video import Undo");}
 Roundtrip(s,b=>game==GameVersion.Pt?new SAV4Pt(b):new SAV4HGSS(b),"dlc4","video:0");Console.WriteLine("PASS "+game+" encrypted/decrypted battle videos");
}
foreach(bool japanese in new[]{false,true}){
 var sav=new SAV4BR();typeof(SAV4BR).GetField("Container",BindingFlags.NonPublic|BindingFlags.Instance)!.SetValue(sav,new Memory<byte>(new byte[SaveUtil.SIZE_G4BR]));sav.Language=japanese?1:2;var s=Session(sav);var before=sav.Data.ToArray();var page=Req(s,new{op="extraPage",kind="passes"});Assert(before.SequenceEqual(sav.Data.ToArray()),"Pass read purity");Assert(page.GetProperty("entries").GetArrayLength()==BattlePassAccessor.PASS_COUNT*7,"All passes and teams");
 Edit(s,"passes","pass:0",("Name","Kai"),("Model","1"),("Issued","true"),("Available","true"),("Language",japanese?"0":"1"));Edit(s,"passes","pass:0",("PlayerID","FEDCBA9876543210"),("TID","65535"),("SID","12345"),("Greeting","Hello"),("SentOut","Go!\nPartner!"),("SelfIntroduction","KeepSake\nFriends"),("RecordWiFiBattles","12345"));Assert(Value(s,"passes","pass:0","PlayerID")=="FEDCBA9876543210","Full-width Player ID");Assert(Value(s,"passes","pass:0","SentOut")=="Go!\nPartner!","Pass multiline");

 Edit(s,"passes","pass:0",("Language",japanese?"1":"0"));Assert(Value(s,"passes","pass:0","SelfIntroduction")=="KeepSake\nFriends","Language preserves introduction");Assert(((SAV4BR)Current(s)).BattlePasses[0].SelfIntroduction.StartsWith(StringConverter4GC.Proportional)==japanese,"Language updates proportional prefix");Req(s,new{op="undo"});before=Current(s).Data.ToArray();Reject(()=>Edit(s,"passes","pass:0",("RegionCode","日本")),"Reject region truncation");Assert(before.SequenceEqual(Current(s).Data.ToArray()),"Region rejection atomicity");
 var fields=Row(s,"passes","pass:0").GetProperty("fields").EnumerateArray().ToArray();foreach(var f in fields.Where(f=>f.GetProperty("group").GetString()=="Appearance"&&f.GetProperty("kind").GetString()=="enum")){string key=f.GetProperty("id").GetString()!;if(key=="Model")continue;string value=f.GetProperty("choices").EnumerateArray().Last().GetProperty("value").GetString()!;Edit(s,"passes","pass:0",(key,value));Assert(Value(s,"passes","pass:0",key)==value,"Pass gear "+key);}
 var pk=new BK4{Species=25,CurrentLevel=50,Move1=85};pk.RefreshChecksum();entityField.SetValue(s,pk);Act(s,"passes","member:0:5","set");Assert(((SAV4BR)Current(s)).BattlePasses[0].GetPartySlotPresent(0),"Pass team compaction");Assert(((SAV4BR)Current(s)).BattlePasses[0].GetPartySlotAtIndex(0).Species==25,"Pass team copy");var mon=Export(s,"passes","member:0:0");Import(s,"passes","member:0:1",mon);Assert(((SAV4BR)Current(s)).BattlePasses[0].GetPartySlotAtIndex(1).Species==25,"Pass Pokémon import");Act(s,"passes","member:0:0","clear");Assert(((SAV4BR)Current(s)).BattlePasses[0].GetPartySlotPresent(0)&&!((SAV4BR)Current(s)).BattlePasses[0].GetPartySlotPresent(1),"Pass team delete compaction");Req(s,new{op="undo"});
 before=Current(s).Data.ToArray();Req(s,new{op="extraView",kind="passes",id="member:0:0",revision=Rev(s)});Assert(Current(s).Data.SequenceEqual(before),"Pass View does not change save");Assert(((PKM)entityField.GetValue(s)!).Species==25,"Pass View Pokémon");
 string file=Export(s,"passes","pass:0");Import(s,"passes","pass:1",file);Act(s,"passes","pass:1","up");Assert(Value(s,"passes","pass:0","Name")=="Kai","Pass swap");Act(s,"passes","","custom");Act(s,"passes","","rental");Assert(((SAV4BR)Current(s)).BattlePasses[0].Available,"Pass unlock");Reject(()=>Act(s,"passes","pass:"+((SAV4BR)Current(s)).BattlePasses.PASS_START_RENTAL,"delete"),"Protected rental");Reject(()=>Edit(s,"passes","pass:0",("Greeting",new string('x',26))),"Pass text limit");
 Roundtrip(s,b=>new SAV4BR(b),"passes","pass:0");File.WriteAllBytes(Path.Combine(scratch,japanese?"PBR-JP.sav":"PBR-EN.sav"),Current(s).Write().ToArray());Console.WriteLine("PASS Battle Pass "+(japanese?"Japanese":"English"));
}
Console.WriteLine($"PASS {checks} requests/assertions on generated fixtures; scratch {scratch}");
